<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\MySchedule.Communication\MySchedule.Communication.csproj" />
      <ProjectReference Include="..\..\Shared\MySchedule.Exception\MySchedule.Exception.csproj" />
      <ProjectReference Include="..\MySchedule.Domain\MySchedule.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="Mapster" Version="10.0.3" />
    </ItemGroup>

</Project>
